# Generated by Django 3.1.1 on 2020-10-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='dob',
            new_name='issue_time',
        ),
    ]
