# Generated by Django 3.1.1 on 2020-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_auto_20201021_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_email', models.EmailField(max_length=254)),
                ('incidents', models.ManyToManyField(to='incident.Incident')),
            ],
        ),
    ]
