# Generated by Django 3.1.1 on 2020-10-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_developers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developers',
            name='incidents',
        ),
        migrations.AddField(
            model_name='incident',
            name='developer',
            field=models.ManyToManyField(to='incident.Developers'),
        ),
    ]
