# Generated by Django 3.1.1 on 2020-10-28 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_auto_20201024_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='team_number',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
